-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-21 14:34:39 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE atendimento 
	( 
	 id_atendimento             NUMBER (3)  NOT NULL , 
	 data                       TIMESTAMP  NOT NULL , 
	 anotacoes                  VARCHAR2 (300)  NOT NULL , 
	 valor                      NUMBER (10,2)  NOT NULL , 
	 pet_id_pet                 NUMBER (3)  NOT NULL , 
	 status_id_status           NUMBER (3)  NOT NULL , 
	 tipo_atend_id_tipo_atend   NUMBER (3)  NOT NULL , 
	 veterinario_id_veterinario NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE atendimento 
	ADD CONSTRAINT atendimento_PK PRIMARY KEY ( id_atendimento ) ;

CREATE TABLE bairro 
	( 
	 id_bairro        NUMBER (3)  NOT NULL , 
	 nome_bairro      VARCHAR2 (30)  NOT NULL , 
	 cidade_id_cidade NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE bairro 
	ADD CONSTRAINT bairro_PK PRIMARY KEY ( id_bairro ) ;

CREATE TABLE cidade 
	( 
	 id_cidade        NUMBER (3)  NOT NULL , 
	 nome_cidade      VARCHAR2 (30)  NOT NULL , 
	 estado_id_estado NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE cidade 
	ADD CONSTRAINT cidade_PK PRIMARY KEY ( id_cidade ) ;

CREATE TABLE clinica 
	( 
	 id_clinica           NUMBER (3)  NOT NULL , 
	 nome                 VARCHAR2 (30)  NOT NULL , 
	 telefone_id_telefone NUMBER (3)  NOT NULL , 
	 endereco_id_endereco NUMBER (3)  NOT NULL 
	) 
;
CREATE UNIQUE INDEX clinica__IDX ON clinica 
	( 
	 telefone_id_telefone ASC 
	) 
;
CREATE UNIQUE INDEX clinica__IDXv1 ON clinica 
	( 
	 endereco_id_endereco ASC 
	) 
;

ALTER TABLE clinica 
	ADD CONSTRAINT clinica_PK PRIMARY KEY ( id_clinica ) ;

CREATE TABLE endereco 
	( 
	 id_endereco      NUMBER (3)  NOT NULL , 
	 cep              VARCHAR2 (8)  NOT NULL , 
	 rua              VARCHAR2 (150)  NOT NULL , 
	 numero           VARCHAR2 (5)  NOT NULL , 
	 bairro_id_bairro NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE endereco 
	ADD CONSTRAINT endereco_PK PRIMARY KEY ( id_endereco ) ;

CREATE TABLE estado 
	( 
	 id_estado   NUMBER (3)  NOT NULL , 
	 nome_estado VARCHAR2 (30)  NOT NULL 
	) 
;

ALTER TABLE estado 
	ADD CONSTRAINT estado_PK PRIMARY KEY ( id_estado ) ;

CREATE TABLE pet 
	( 
	 id_pet       NUMBER (3)  NOT NULL , 
	 nome         VARCHAR2 (30)  NOT NULL , 
	 idade        NUMBER (2)  NOT NULL , 
	 sexo         VARCHAR2 (1)  NOT NULL , 
	 porte        VARCHAR2 (10)  NOT NULL , 
	 castrado     CHAR (1)  NOT NULL , 
	 raca_id_raca NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE pet 
	ADD 
	CHECK (sexo IN ('F', 'M')) 
;

ALTER TABLE pet 
	ADD 
	CHECK (porte IN ('GRANDE', 'MEDIO', 'PEQUENO')) 
;

ALTER TABLE pet 
	ADD CONSTRAINT pet_PK PRIMARY KEY ( id_pet ) ;

CREATE TABLE raca 
	( 
	 id_raca   NUMBER (3)  NOT NULL , 
	 nome_raca VARCHAR2 (30)  NOT NULL 
	) 
;

ALTER TABLE raca 
	ADD CONSTRAINT raca_PK PRIMARY KEY ( id_raca ) ;

CREATE TABLE status 
	( 
	 id_status   NUMBER (3)  NOT NULL , 
	 nome_status VARCHAR2 (15)  NOT NULL 
	) 
;

ALTER TABLE status 
	ADD 
	CHECK (nome_status IN ('CONCLUIDO', 'EXPIRADO', 'PENDENTE')) 
;

ALTER TABLE status 
	ADD CONSTRAINT status_PK PRIMARY KEY ( id_status ) ;

CREATE TABLE tarefa 
	( 
	 id_tarefa                  NUMBER (3)  NOT NULL , 
	 titulo                     VARCHAR2 (30)  NOT NULL , 
	 pontos_tarefa              NUMBER (3)  NOT NULL , 
	 descricao                  VARCHAR2 (200)  NOT NULL , 
	 criacao                    TIMESTAMP  NOT NULL , 
	 prazo                      TIMESTAMP  NOT NULL , 
	 conclusao                  TIMESTAMP , 
	 usuario_id_usuario         NUMBER (3) , 
	 pet_id_pet                 NUMBER (3)  NOT NULL , 
	 status_id_status           NUMBER (3)  NOT NULL , 
	 veterinario_id_veterinario NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE tarefa 
	ADD CONSTRAINT tarefa_PK PRIMARY KEY ( id_tarefa ) ;

CREATE TABLE telefone 
	( 
	 id_telefone NUMBER (3)  NOT NULL , 
	 num_ddd     VARCHAR2 (2)  NOT NULL , 
	 num_tel     VARCHAR2 (9)  NOT NULL 
	) 
;

ALTER TABLE telefone 
	ADD CONSTRAINT telefone_PK PRIMARY KEY ( id_telefone ) ;

CREATE TABLE tipo_atend 
	( 
	 id_tipo_atend NUMBER (3)  NOT NULL , 
	 tipo          VARCHAR2 (30)  NOT NULL 
	) 
;

ALTER TABLE tipo_atend 
	ADD CONSTRAINT tipo_atend_PK PRIMARY KEY ( id_tipo_atend ) ;

CREATE TABLE usuario 
	( 
	 id_usuario           NUMBER (3)  NOT NULL , 
	 nome                 VARCHAR2 (100)  NOT NULL , 
	 email                VARCHAR2 (50)  NOT NULL , 
	 senha                VARCHAR2 (20)  NOT NULL , 
	 telefone_id_telefone NUMBER (3)
	) 
;
CREATE UNIQUE INDEX usuario__IDX ON usuario 
	( 
	 telefone_id_telefone ASC 
	) 
;

ALTER TABLE usuario 
	ADD CONSTRAINT usuario_PK PRIMARY KEY ( id_usuario ) ;

CREATE TABLE usuario_endereco 
	( 
	 usuario_id_usuario   NUMBER (3)  NOT NULL , 
	 endereco_id_endereco NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE usuario_endereco 
	ADD CONSTRAINT usuario_endereco_PK PRIMARY KEY ( usuario_id_usuario, endereco_id_endereco ) ;

CREATE TABLE usuario_pet 
	( 
	 usuario_id_usuario NUMBER (3)  NOT NULL , 
	 pet_id_pet         NUMBER (3)  NOT NULL , 
	 respon_princ       CHAR (1)  NOT NULL 
	) 
;

ALTER TABLE usuario_pet 
	ADD CONSTRAINT usuario_pet_PK PRIMARY KEY ( usuario_id_usuario, pet_id_pet ) ;

CREATE TABLE veterinario 
	( 
	 id_veterinario       NUMBER (3)  NOT NULL , 
	 nome                 VARCHAR2 (100)  NOT NULL , 
	 email                VARCHAR2 (50)  NOT NULL , 
	 senha                VARCHAR2 (20)  NOT NULL , 
	 telefone_id_telefone NUMBER (3)  NOT NULL , 
	 clinica_id_clinica   NUMBER (3)
	) 
;
CREATE UNIQUE INDEX veterinario__IDX ON veterinario 
	( 
	 telefone_id_telefone ASC 
	) 
;

ALTER TABLE veterinario 
	ADD CONSTRAINT veterinario_PK PRIMARY KEY ( id_veterinario ) ;

ALTER TABLE atendimento 
	ADD CONSTRAINT atendimento_pet_FK FOREIGN KEY 
	( 
	 pet_id_pet
	) 
	REFERENCES pet 
	( 
	 id_pet
	) 
;

ALTER TABLE atendimento 
	ADD CONSTRAINT atendimento_status_FK FOREIGN KEY 
	( 
	 status_id_status
	) 
	REFERENCES status 
	( 
	 id_status
	) 
;

ALTER TABLE atendimento 
	ADD CONSTRAINT atendimento_tipo_atend_FK FOREIGN KEY 
	( 
	 tipo_atend_id_tipo_atend
	) 
	REFERENCES tipo_atend 
	( 
	 id_tipo_atend
	) 
;

ALTER TABLE atendimento 
	ADD CONSTRAINT atendimento_veterinario_FK FOREIGN KEY 
	( 
	 veterinario_id_veterinario
	) 
	REFERENCES veterinario 
	( 
	 id_veterinario
	) 
;

ALTER TABLE bairro 
	ADD CONSTRAINT bairro_cidade_FK FOREIGN KEY 
	( 
	 cidade_id_cidade
	) 
	REFERENCES cidade 
	( 
	 id_cidade
	) 
;

ALTER TABLE cidade 
	ADD CONSTRAINT cidade_estado_FK FOREIGN KEY 
	( 
	 estado_id_estado
	) 
	REFERENCES estado 
	( 
	 id_estado
	) 
;

ALTER TABLE clinica 
	ADD CONSTRAINT clinica_endereco_FK FOREIGN KEY 
	( 
	 endereco_id_endereco
	) 
	REFERENCES endereco 
	( 
	 id_endereco
	) 
;

ALTER TABLE clinica 
	ADD CONSTRAINT clinica_telefone_FK FOREIGN KEY 
	( 
	 telefone_id_telefone
	) 
	REFERENCES telefone 
	( 
	 id_telefone
	) 
;

ALTER TABLE endereco 
	ADD CONSTRAINT endereco_bairro_FK FOREIGN KEY 
	( 
	 bairro_id_bairro
	) 
	REFERENCES bairro 
	( 
	 id_bairro
	) 
;

ALTER TABLE pet 
	ADD CONSTRAINT pet_raca_FK FOREIGN KEY 
	( 
	 raca_id_raca
	) 
	REFERENCES raca 
	( 
	 id_raca
	) 
;

ALTER TABLE tarefa 
	ADD CONSTRAINT tarefa_pet_FK FOREIGN KEY 
	( 
	 pet_id_pet
	) 
	REFERENCES pet 
	( 
	 id_pet
	) 
;

ALTER TABLE tarefa 
	ADD CONSTRAINT tarefa_status_FK FOREIGN KEY 
	( 
	 status_id_status
	) 
	REFERENCES status 
	( 
	 id_status
	) 
;

ALTER TABLE tarefa 
	ADD CONSTRAINT tarefa_usuario_FK FOREIGN KEY 
	( 
	 usuario_id_usuario
	) 
	REFERENCES usuario 
	( 
	 id_usuario
	) 
;

ALTER TABLE tarefa 
	ADD CONSTRAINT tarefa_veterinario_FK FOREIGN KEY 
	( 
	 veterinario_id_veterinario
	) 
	REFERENCES veterinario 
	( 
	 id_veterinario
	) 
;

ALTER TABLE usuario_endereco 
	ADD CONSTRAINT usuario_endereco_endereco_FK FOREIGN KEY 
	( 
	 endereco_id_endereco
	) 
	REFERENCES endereco 
	( 
	 id_endereco
	) 
;

ALTER TABLE usuario_endereco 
	ADD CONSTRAINT usuario_endereco_usuario_FK FOREIGN KEY 
	( 
	 usuario_id_usuario
	) 
	REFERENCES usuario 
	( 
	 id_usuario
	) 
;

ALTER TABLE usuario_pet 
	ADD CONSTRAINT usuario_pet_pet_FK FOREIGN KEY 
	( 
	 pet_id_pet
	) 
	REFERENCES pet 
	( 
	 id_pet
	) 
;

ALTER TABLE usuario_pet 
	ADD CONSTRAINT usuario_pet_usuario_FK FOREIGN KEY 
	( 
	 usuario_id_usuario
	) 
	REFERENCES usuario 
	( 
	 id_usuario
	) 
;

ALTER TABLE usuario 
	ADD CONSTRAINT usuario_telefone_FK FOREIGN KEY 
	( 
	 telefone_id_telefone
	) 
	REFERENCES telefone 
	( 
	 id_telefone
	) 
;

ALTER TABLE veterinario 
	ADD CONSTRAINT veterinario_clinica_FK FOREIGN KEY 
	( 
	 clinica_id_clinica
	) 
	REFERENCES clinica 
	( 
	 id_clinica
	) 
;

ALTER TABLE veterinario 
	ADD CONSTRAINT veterinario_telefone_FK FOREIGN KEY 
	( 
	 telefone_id_telefone
	) 
	REFERENCES telefone 
	( 
	 id_telefone
	) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             5
-- ALTER TABLE                             40
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
