-- =========================================================================
-- PROJETO CHALLENGE PETGUARDIAN
-- SPRINT 1 - DATABASE ADVANCED
-- CONSOLIDADO DOS SCRIPTS DE ENTREGA
-- =========================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;


-- =========================================================================
-- INÍCIO DO ARQUIVO: 01_ddl_tabelas.sql
-- =========================================================================

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-21 14:34:39 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE atendimento 
	( 
	 id_atendimento             NUMBER (3)  NOT NULL , 
	 data                       TIMESTAMP  NOT NULL , 
	 anotacoes                  VARCHAR2 (300)  NOT NULL , 
	 valor                      NUMBER (10,2)  NOT NULL , 
	 pet_id_pet                 NUMBER (3)  NOT NULL , 
	 status_id_status           NUMBER (3)  NOT NULL , 
	 tipo_atend_id_tipo_atend   NUMBER (3)  NOT NULL , 
	 veterinario_id_veterinario NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE atendimento 
	ADD CONSTRAINT atendimento_PK PRIMARY KEY ( id_atendimento ) ;

CREATE TABLE bairro 
	( 
	 id_bairro        NUMBER (3)  NOT NULL , 
	 nome_bairro      VARCHAR2 (30)  NOT NULL , 
	 cidade_id_cidade NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE bairro 
	ADD CONSTRAINT bairro_PK PRIMARY KEY ( id_bairro ) ;

CREATE TABLE cidade 
	( 
	 id_cidade        NUMBER (3)  NOT NULL , 
	 nome_cidade      VARCHAR2 (30)  NOT NULL , 
	 estado_id_estado NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE cidade 
	ADD CONSTRAINT cidade_PK PRIMARY KEY ( id_cidade ) ;

CREATE TABLE clinica 
	( 
	 id_clinica           NUMBER (3)  NOT NULL , 
	 nome                 VARCHAR2 (30)  NOT NULL , 
	 telefone_id_telefone NUMBER (3)  NOT NULL , 
	 endereco_id_endereco NUMBER (3)  NOT NULL 
	) 
;
CREATE UNIQUE INDEX clinica__IDX ON clinica 
	( 
	 telefone_id_telefone ASC 
	) 
;
CREATE UNIQUE INDEX clinica__IDXv1 ON clinica 
	( 
	 endereco_id_endereco ASC 
	) 
;

ALTER TABLE clinica 
	ADD CONSTRAINT clinica_PK PRIMARY KEY ( id_clinica ) ;

CREATE TABLE endereco 
	( 
	 id_endereco      NUMBER (3)  NOT NULL , 
	 cep              VARCHAR2 (8)  NOT NULL , 
	 rua              VARCHAR2 (150)  NOT NULL , 
	 numero           VARCHAR2 (5)  NOT NULL , 
	 bairro_id_bairro NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE endereco 
	ADD CONSTRAINT endereco_PK PRIMARY KEY ( id_endereco ) ;

CREATE TABLE estado 
	( 
	 id_estado   NUMBER (3)  NOT NULL , 
	 nome_estado VARCHAR2 (30)  NOT NULL 
	) 
;

ALTER TABLE estado 
	ADD CONSTRAINT estado_PK PRIMARY KEY ( id_estado ) ;

CREATE TABLE pet 
	( 
	 id_pet       NUMBER (3)  NOT NULL , 
	 nome         VARCHAR2 (30)  NOT NULL , 
	 idade        NUMBER (2)  NOT NULL , 
	 sexo         VARCHAR2 (1)  NOT NULL , 
	 porte        VARCHAR2 (10)  NOT NULL , 
	 castrado     CHAR (1)  NOT NULL , 
	 raca_id_raca NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE pet 
	ADD 
	CHECK (sexo IN ('F', 'M')) 
;

ALTER TABLE pet 
	ADD 
	CHECK (porte IN ('GRANDE', 'MEDIO', 'PEQUENO')) 
;

ALTER TABLE pet 
	ADD CONSTRAINT pet_PK PRIMARY KEY ( id_pet ) ;

CREATE TABLE raca 
	( 
	 id_raca   NUMBER (3)  NOT NULL , 
	 nome_raca VARCHAR2 (30)  NOT NULL 
	) 
;

ALTER TABLE raca 
	ADD CONSTRAINT raca_PK PRIMARY KEY ( id_raca ) ;

CREATE TABLE status 
	( 
	 id_status   NUMBER (3)  NOT NULL , 
	 nome_status VARCHAR2 (15)  NOT NULL 
	) 
;

ALTER TABLE status 
	ADD 
	CHECK (nome_status IN ('CONCLUIDO', 'EXPIRADO', 'PENDENTE')) 
;

ALTER TABLE status 
	ADD CONSTRAINT status_PK PRIMARY KEY ( id_status ) ;

CREATE TABLE tarefa 
	( 
	 id_tarefa                  NUMBER (3)  NOT NULL , 
	 titulo                     VARCHAR2 (30)  NOT NULL , 
	 pontos_tarefa              NUMBER (3)  NOT NULL , 
	 descricao                  VARCHAR2 (200)  NOT NULL , 
	 criacao                    TIMESTAMP  NOT NULL , 
	 prazo                      TIMESTAMP  NOT NULL , 
	 conclusao                  TIMESTAMP , 
	 usuario_id_usuario         NUMBER (3) , 
	 pet_id_pet                 NUMBER (3)  NOT NULL , 
	 status_id_status           NUMBER (3)  NOT NULL , 
	 veterinario_id_veterinario NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE tarefa 
	ADD CONSTRAINT tarefa_PK PRIMARY KEY ( id_tarefa ) ;

CREATE TABLE telefone 
	( 
	 id_telefone NUMBER (3)  NOT NULL , 
	 num_ddd     VARCHAR2 (2)  NOT NULL , 
	 num_tel     VARCHAR2 (9)  NOT NULL 
	) 
;

ALTER TABLE telefone 
	ADD CONSTRAINT telefone_PK PRIMARY KEY ( id_telefone ) ;

CREATE TABLE tipo_atend 
	( 
	 id_tipo_atend NUMBER (3)  NOT NULL , 
	 tipo          VARCHAR2 (30)  NOT NULL 
	) 
;

ALTER TABLE tipo_atend 
	ADD CONSTRAINT tipo_atend_PK PRIMARY KEY ( id_tipo_atend ) ;

CREATE TABLE usuario 
	( 
	 id_usuario           NUMBER (3)  NOT NULL , 
	 nome                 VARCHAR2 (100)  NOT NULL , 
	 email                VARCHAR2 (50)  NOT NULL , 
	 senha                VARCHAR2 (20)  NOT NULL , 
	 telefone_id_telefone NUMBER (3)
	) 
;
CREATE UNIQUE INDEX usuario__IDX ON usuario 
	( 
	 telefone_id_telefone ASC 
	) 
;

ALTER TABLE usuario 
	ADD CONSTRAINT usuario_PK PRIMARY KEY ( id_usuario ) ;

CREATE TABLE usuario_endereco 
	( 
	 usuario_id_usuario   NUMBER (3)  NOT NULL , 
	 endereco_id_endereco NUMBER (3)  NOT NULL 
	) 
;

ALTER TABLE usuario_endereco 
	ADD CONSTRAINT usuario_endereco_PK PRIMARY KEY ( usuario_id_usuario, endereco_id_endereco ) ;

CREATE TABLE usuario_pet 
	( 
	 usuario_id_usuario NUMBER (3)  NOT NULL , 
	 pet_id_pet         NUMBER (3)  NOT NULL , 
	 respon_princ       CHAR (1)  NOT NULL 
	) 
;

ALTER TABLE usuario_pet 
	ADD CONSTRAINT usuario_pet_PK PRIMARY KEY ( usuario_id_usuario, pet_id_pet ) ;

CREATE TABLE veterinario 
	( 
	 id_veterinario       NUMBER (3)  NOT NULL , 
	 nome                 VARCHAR2 (100)  NOT NULL , 
	 email                VARCHAR2 (50)  NOT NULL , 
	 senha                VARCHAR2 (20)  NOT NULL , 
	 telefone_id_telefone NUMBER (3)  NOT NULL , 
	 clinica_id_clinica   NUMBER (3)
	) 
;
CREATE UNIQUE INDEX veterinario__IDX ON veterinario 
	( 
	 telefone_id_telefone ASC 
	) 
;

ALTER TABLE veterinario 
	ADD CONSTRAINT veterinario_PK PRIMARY KEY ( id_veterinario ) ;

ALTER TABLE atendimento 
	ADD CONSTRAINT atendimento_pet_FK FOREIGN KEY 
	( 
	 pet_id_pet
	) 
	REFERENCES pet 
	( 
	 id_pet
	) 
;

ALTER TABLE atendimento 
	ADD CONSTRAINT atendimento_status_FK FOREIGN KEY 
	( 
	 status_id_status
	) 
	REFERENCES status 
	( 
	 id_status
	) 
;

ALTER TABLE atendimento 
	ADD CONSTRAINT atendimento_tipo_atend_FK FOREIGN KEY 
	( 
	 tipo_atend_id_tipo_atend
	) 
	REFERENCES tipo_atend 
	( 
	 id_tipo_atend
	) 
;

ALTER TABLE atendimento 
	ADD CONSTRAINT atendimento_veterinario_FK FOREIGN KEY 
	( 
	 veterinario_id_veterinario
	) 
	REFERENCES veterinario 
	( 
	 id_veterinario
	) 
;

ALTER TABLE bairro 
	ADD CONSTRAINT bairro_cidade_FK FOREIGN KEY 
	( 
	 cidade_id_cidade
	) 
	REFERENCES cidade 
	( 
	 id_cidade
	) 
;

ALTER TABLE cidade 
	ADD CONSTRAINT cidade_estado_FK FOREIGN KEY 
	( 
	 estado_id_estado
	) 
	REFERENCES estado 
	( 
	 id_estado
	) 
;

ALTER TABLE clinica 
	ADD CONSTRAINT clinica_endereco_FK FOREIGN KEY 
	( 
	 endereco_id_endereco
	) 
	REFERENCES endereco 
	( 
	 id_endereco
	) 
;

ALTER TABLE clinica 
	ADD CONSTRAINT clinica_telefone_FK FOREIGN KEY 
	( 
	 telefone_id_telefone
	) 
	REFERENCES telefone 
	( 
	 id_telefone
	) 
;

ALTER TABLE endereco 
	ADD CONSTRAINT endereco_bairro_FK FOREIGN KEY 
	( 
	 bairro_id_bairro
	) 
	REFERENCES bairro 
	( 
	 id_bairro
	) 
;

ALTER TABLE pet 
	ADD CONSTRAINT pet_raca_FK FOREIGN KEY 
	( 
	 raca_id_raca
	) 
	REFERENCES raca 
	( 
	 id_raca
	) 
;

ALTER TABLE tarefa 
	ADD CONSTRAINT tarefa_pet_FK FOREIGN KEY 
	( 
	 pet_id_pet
	) 
	REFERENCES pet 
	( 
	 id_pet
	) 
;

ALTER TABLE tarefa 
	ADD CONSTRAINT tarefa_status_FK FOREIGN KEY 
	( 
	 status_id_status
	) 
	REFERENCES status 
	( 
	 id_status
	) 
;

ALTER TABLE tarefa 
	ADD CONSTRAINT tarefa_usuario_FK FOREIGN KEY 
	( 
	 usuario_id_usuario
	) 
	REFERENCES usuario 
	( 
	 id_usuario
	) 
;

ALTER TABLE tarefa 
	ADD CONSTRAINT tarefa_veterinario_FK FOREIGN KEY 
	( 
	 veterinario_id_veterinario
	) 
	REFERENCES veterinario 
	( 
	 id_veterinario
	) 
;

ALTER TABLE usuario_endereco 
	ADD CONSTRAINT usuario_endereco_endereco_FK FOREIGN KEY 
	( 
	 endereco_id_endereco
	) 
	REFERENCES endereco 
	( 
	 id_endereco
	) 
;

ALTER TABLE usuario_endereco 
	ADD CONSTRAINT usuario_endereco_usuario_FK FOREIGN KEY 
	( 
	 usuario_id_usuario
	) 
	REFERENCES usuario 
	( 
	 id_usuario
	) 
;

ALTER TABLE usuario_pet 
	ADD CONSTRAINT usuario_pet_pet_FK FOREIGN KEY 
	( 
	 pet_id_pet
	) 
	REFERENCES pet 
	( 
	 id_pet
	) 
;

ALTER TABLE usuario_pet 
	ADD CONSTRAINT usuario_pet_usuario_FK FOREIGN KEY 
	( 
	 usuario_id_usuario
	) 
	REFERENCES usuario 
	( 
	 id_usuario
	) 
;

ALTER TABLE usuario 
	ADD CONSTRAINT usuario_telefone_FK FOREIGN KEY 
	( 
	 telefone_id_telefone
	) 
	REFERENCES telefone 
	( 
	 id_telefone
	) 
;

ALTER TABLE veterinario 
	ADD CONSTRAINT veterinario_clinica_FK FOREIGN KEY 
	( 
	 clinica_id_clinica
	) 
	REFERENCES clinica 
	( 
	 id_clinica
	) 
;

ALTER TABLE veterinario 
	ADD CONSTRAINT veterinario_telefone_FK FOREIGN KEY 
	( 
	 telefone_id_telefone
	) 
	REFERENCES telefone 
	( 
	 id_telefone
	) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             5
-- ALTER TABLE                             40
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


-- =========================================================================
-- FIM DO ARQUIVO: 01_ddl_tabelas.sql
-- =========================================================================


-- =========================================================================
-- INÍCIO DO ARQUIVO: 02_ddl_logs.sql
-- =========================================================================

-- 02_ddl_logs.sql
-- Criação da tabela de logs para registro de erros (Oracle 11g compatível)

CREATE TABLE log_erros (
    id_log         NUMBER(12) NOT NULL,
    nome_procedure VARCHAR2(100) NOT NULL,
    usuario        VARCHAR2(100) NOT NULL,
    data_erro      TIMESTAMP DEFAULT SYSTIMESTAMP,
    codigo_erro    NUMBER,
    mensagem_erro  VARCHAR2(4000)
);

CREATE SEQUENCE log_erros_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER trg_log_erros_bi
BEFORE INSERT ON log_erros
FOR EACH ROW
BEGIN
    IF :NEW.id_log IS NULL THEN
        SELECT log_erros_seq.NEXTVAL INTO :NEW.id_log FROM DUAL;
    END IF;
END;
/


-- =========================================================================
-- FIM DO ARQUIVO: 02_ddl_logs.sql
-- =========================================================================


-- =========================================================================
-- INÍCIO DO ARQUIVO: 03_procedures_carga.sql
-- =========================================================================

-- 03_procedures_carga.sql
-- Procedures para carga de dados em cada tabela, com tratamento de exceções e registro em log
-- Inclui sequences auxiliares para facilitar geração de PK quando necessário

-- Sequences para PK (úteis nas procedures de carga)
BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_pet START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_raca START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_telefone START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_endereco START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_bairro START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_cidade START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_estado START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_clinica START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_veterinario START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_usuario START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_tipo_atend START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_status START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_tarefa START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_atendimento START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
        RAISE;
    END IF;
END;
/

-- Procedure helper para gravar logs
CREATE OR REPLACE PROCEDURE prc_grava_log(
    p_nome_procedure IN VARCHAR2,
    p_usuario        IN VARCHAR2,
    p_codigo_erro    IN NUMBER,
    p_mensagem_erro  IN VARCHAR2
) AS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO log_erros (id_log, nome_procedure, usuario, data_erro, codigo_erro, mensagem_erro)
    VALUES (log_erros_seq.NEXTVAL, p_nome_procedure, NVL(p_usuario, USER), SYSTIMESTAMP, p_codigo_erro, p_mensagem_erro);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END prc_grava_log;
/

-- Procedure: inserir pet
CREATE OR REPLACE PROCEDURE prc_insere_pet(
    p_id_pet       IN NUMBER DEFAULT NULL,
    p_nome         IN VARCHAR2,
    p_idade        IN NUMBER,
    p_sexo         IN VARCHAR2,
    p_porte        IN VARCHAR2,
    p_castrado     IN CHAR,
    p_raca_id_raca IN NUMBER
) AS
    v_id NUMBER;
BEGIN
    IF p_id_pet IS NULL THEN
        SELECT seq_pet.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_pet;
    END IF;

    INSERT INTO pet (id_pet, nome, idade, sexo, porte, castrado, raca_id_raca)
    VALUES (v_id, p_nome, p_idade, p_sexo, p_porte, p_castrado, p_raca_id_raca);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_pet', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_pet', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_pet', USER, SQLCODE, SQLERRM);
END prc_insere_pet;
/

-- Procedure: inserir raca
CREATE OR REPLACE PROCEDURE prc_insere_raca(
    p_id_raca IN NUMBER DEFAULT NULL,
    p_nome_raca IN VARCHAR2
) AS
    v_id NUMBER;
BEGIN
    IF p_id_raca IS NULL THEN
        SELECT seq_raca.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_raca;
    END IF;
    INSERT INTO raca (id_raca, nome_raca) VALUES (v_id, p_nome_raca);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_raca', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_raca', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_raca', USER, SQLCODE, SQLERRM);
END prc_insere_raca;
/

-- Procedure: inserir telefone
CREATE OR REPLACE PROCEDURE prc_insere_telefone(
    p_id_telefone IN NUMBER DEFAULT NULL,
    p_num_ddd IN VARCHAR2,
    p_num_tel IN VARCHAR2
) AS
    v_id NUMBER;
BEGIN
    IF p_id_telefone IS NULL THEN
        SELECT seq_telefone.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_telefone;
    END IF;
    INSERT INTO telefone (id_telefone, num_ddd, num_tel) VALUES (v_id, p_num_ddd, p_num_tel);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_telefone', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_telefone', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_telefone', USER, SQLCODE, SQLERRM);
END prc_insere_telefone;
/

-- Procedure: inserir usuario
CREATE OR REPLACE PROCEDURE prc_insere_usuario(
    p_id_usuario IN NUMBER DEFAULT NULL,
    p_nome IN VARCHAR2,
    p_email IN VARCHAR2,
    p_senha IN VARCHAR2,
    p_telefone_id_telefone IN NUMBER
) AS
    v_id NUMBER;
BEGIN
    IF p_id_usuario IS NULL THEN
        SELECT seq_usuario.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_usuario;
    END IF;
    INSERT INTO usuario (id_usuario, nome, email, senha, telefone_id_telefone)
    VALUES (v_id, p_nome, p_email, p_senha, p_telefone_id_telefone);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_usuario', USER, SQLCODE, SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_usuario', USER, SQLCODE, SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_usuario', USER, SQLCODE, SQLERRM);
END prc_insere_usuario;
/

-- Procedure: inserir endereco
CREATE OR REPLACE PROCEDURE prc_insere_endereco(
    p_id_endereco IN NUMBER DEFAULT NULL,
    p_cep IN VARCHAR2,
    p_rua IN VARCHAR2,
    p_numero IN VARCHAR2,
    p_bairro_id_bairro IN NUMBER
) AS
    v_id NUMBER;
BEGIN
    IF p_id_endereco IS NULL THEN
        SELECT seq_endereco.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_endereco;
    END IF;
    INSERT INTO endereco (id_endereco, cep, rua, numero, bairro_id_bairro)
    VALUES (v_id, p_cep, p_rua, p_numero, p_bairro_id_bairro);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_endereco', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_endereco', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_endereco', USER, SQLCODE, SQLERRM);
END prc_insere_endereco;
/

-- Procedure: inserir bairro
CREATE OR REPLACE PROCEDURE prc_insere_bairro(
    p_id_bairro IN NUMBER DEFAULT NULL,
    p_nome_bairro IN VARCHAR2,
    p_cidade_id_cidade IN NUMBER
) AS
    v_id NUMBER;
BEGIN
    IF p_id_bairro IS NULL THEN
        SELECT seq_bairro.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_bairro;
    END IF;
    INSERT INTO bairro (id_bairro, nome_bairro, cidade_id_cidade)
    VALUES (v_id, p_nome_bairro, p_cidade_id_cidade);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_bairro', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_bairro', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_bairro', USER, SQLCODE, SQLERRM);
END prc_insere_bairro;
/

-- Procedure: inserir cidade
CREATE OR REPLACE PROCEDURE prc_insere_cidade(
    p_id_cidade IN NUMBER DEFAULT NULL,
    p_nome_cidade IN VARCHAR2,
    p_estado_id_estado IN NUMBER
) AS
    v_id NUMBER;
BEGIN
    IF p_id_cidade IS NULL THEN
        SELECT seq_cidade.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_cidade;
    END IF;
    INSERT INTO cidade (id_cidade, nome_cidade, estado_id_estado)
    VALUES (v_id, p_nome_cidade, p_estado_id_estado);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_cidade', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_cidade', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_cidade', USER, SQLCODE, SQLERRM);
END prc_insere_cidade;
/

-- Procedure: inserir estado
CREATE OR REPLACE PROCEDURE prc_insere_estado(
    p_id_estado IN NUMBER DEFAULT NULL,
    p_nome_estado IN VARCHAR2
) AS
    v_id NUMBER;
BEGIN
    IF p_id_estado IS NULL THEN
        SELECT seq_estado.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_estado;
    END IF;
    INSERT INTO estado (id_estado, nome_estado) VALUES (v_id, p_nome_estado);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_estado', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_estado', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_estado', USER, SQLCODE, SQLERRM);
END prc_insere_estado;
/

-- Procedure: inserir clinica
CREATE OR REPLACE PROCEDURE prc_insere_clinica(
    p_id_clinica IN NUMBER DEFAULT NULL,
    p_nome IN VARCHAR2,
    p_telefone_id_telefone IN NUMBER,
    p_endereco_id_endereco IN NUMBER
) AS
    v_id NUMBER;
BEGIN
    IF p_id_clinica IS NULL THEN
        SELECT seq_clinica.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_clinica;
    END IF;
    INSERT INTO clinica (id_clinica, nome, telefone_id_telefone, endereco_id_endereco)
    VALUES (v_id, p_nome, p_telefone_id_telefone, p_endereco_id_endereco);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_clinica', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_clinica', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_clinica', USER, SQLCODE, SQLERRM);
END prc_insere_clinica;
/

-- Procedure: inserir veterinario
CREATE OR REPLACE PROCEDURE prc_insere_veterinario(
    p_id_veterinario IN NUMBER DEFAULT NULL,
    p_nome IN VARCHAR2,
    p_email IN VARCHAR2,
    p_senha IN VARCHAR2,
    p_telefone_id_telefone IN NUMBER,
    p_clinica_id_clinica IN NUMBER
) AS
    v_id NUMBER;
BEGIN
    IF p_id_veterinario IS NULL THEN
        SELECT seq_veterinario.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_veterinario;
    END IF;
    INSERT INTO veterinario (id_veterinario, nome, email, senha, telefone_id_telefone, clinica_id_clinica)
    VALUES (v_id, p_nome, p_email, p_senha, p_telefone_id_telefone, p_clinica_id_clinica);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_veterinario', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_veterinario', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_veterinario', USER, SQLCODE, SQLERRM);
END prc_insere_veterinario;
/

-- Procedure: inserir tipo_atend
CREATE OR REPLACE PROCEDURE prc_insere_tipo_atend(
    p_id_tipo_atend IN NUMBER DEFAULT NULL,
    p_tipo IN VARCHAR2
) AS
    v_id NUMBER;
BEGIN
    IF p_id_tipo_atend IS NULL THEN
        SELECT seq_tipo_atend.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_tipo_atend;
    END IF;
    INSERT INTO tipo_atend (id_tipo_atend, tipo) VALUES (v_id, p_tipo);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_tipo_atend', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_tipo_atend', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_tipo_atend', USER, SQLCODE, SQLERRM);
END prc_insere_tipo_atend;
/

-- Procedure: inserir status
CREATE OR REPLACE PROCEDURE prc_insere_status(
    p_id_status IN NUMBER DEFAULT NULL,
    p_nome_status IN VARCHAR2
) AS
    v_id NUMBER;
BEGIN
    IF p_id_status IS NULL THEN
        SELECT seq_status.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_status;
    END IF;
    INSERT INTO status (id_status, nome_status) VALUES (v_id, p_nome_status);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_status', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_status', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_status', USER, SQLCODE, SQLERRM);
END prc_insere_status;
/

-- Procedure: inserir tarefa
CREATE OR REPLACE PROCEDURE prc_insere_tarefa(
    p_id_tarefa IN NUMBER DEFAULT NULL,
    p_titulo IN VARCHAR2,
    p_pontos_tarefa IN NUMBER,
    p_descricao IN VARCHAR2,
    p_criacao IN TIMESTAMP DEFAULT SYSTIMESTAMP,
    p_prazo IN TIMESTAMP,
    p_usuario_id_usuario IN NUMBER DEFAULT NULL,
    p_pet_id_pet IN NUMBER,
    p_status_id_status IN NUMBER,
    p_veterinario_id_veterinario IN NUMBER
) AS
    v_id NUMBER;
BEGIN
    IF p_id_tarefa IS NULL THEN
        SELECT seq_tarefa.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_tarefa;
    END IF;
    INSERT INTO tarefa (id_tarefa, titulo, pontos_tarefa, descricao, criacao, prazo, usuario_id_usuario, pet_id_pet, status_id_status, veterinario_id_veterinario)
    VALUES (v_id, p_titulo, p_pontos_tarefa, p_descricao, p_criacao, p_prazo, p_usuario_id_usuario, p_pet_id_pet, p_status_id_status, p_veterinario_id_veterinario);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_tarefa', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_tarefa', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_tarefa', USER, SQLCODE, SQLERRM);
END prc_insere_tarefa;
/

-- Procedure: concluir tarefa (marca usuário e data de conclusão, atualiza status para CONCLUIDO)
CREATE OR REPLACE PROCEDURE prc_concluir_tarefa(
    p_id_tarefa IN NUMBER,
    p_id_usuario IN NUMBER,
    p_data_conclusao IN TIMESTAMP DEFAULT SYSTIMESTAMP
) AS
    v_status_concluido NUMBER;
    v_usuario_atual NUMBER;
BEGIN
    -- Verificar se a tarefa existe e se já possui um concluinte cadastrado
    SELECT usuario_id_usuario INTO v_usuario_atual 
    FROM tarefa 
    WHERE id_tarefa = p_id_tarefa;

    -- Regra de negócio: somente uma pessoa pode concluir a tarefa
    IF v_usuario_atual IS NOT NULL THEN
        prc_grava_log('prc_concluir_tarefa', USER, -20001, 'Tarefa ' || p_id_tarefa || ' ja concluida pelo usuario ' || v_usuario_atual);
        RETURN;
    END IF;

    SELECT id_status INTO v_status_concluido FROM status WHERE nome_status = 'CONCLUIDO' AND ROWNUM = 1;
    UPDATE tarefa
    SET usuario_id_usuario = p_id_usuario,
        conclusao = p_data_conclusao,
        status_id_status = v_status_concluido
    WHERE id_tarefa = p_id_tarefa;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        prc_grava_log('prc_concluir_tarefa', USER, SQLCODE, 'Tarefa ' || p_id_tarefa || ' ou status CONCLUIDO nao encontrado');
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_concluir_tarefa', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_concluir_tarefa', USER, SQLCODE, SQLERRM);
END prc_concluir_tarefa;
/

-- Procedure: inserir atendimento
CREATE OR REPLACE PROCEDURE prc_insere_atendimento(
    p_id_atendimento IN NUMBER DEFAULT NULL,
    p_data IN TIMESTAMP,
    p_anotacoes IN VARCHAR2,
    p_valor IN NUMBER,
    p_pet_id_pet IN NUMBER,
    p_status_id_status IN NUMBER,
    p_tipo_atend_id_tipo_atend IN NUMBER,
    p_veterinario_id_veterinario IN NUMBER
) AS
    v_id NUMBER;
BEGIN
    IF p_id_atendimento IS NULL THEN
        SELECT seq_atendimento.NEXTVAL INTO v_id FROM DUAL;
    ELSE
        v_id := p_id_atendimento;
    END IF;
    INSERT INTO atendimento (id_atendimento, data, anotacoes, valor, pet_id_pet, status_id_status, tipo_atend_id_tipo_atend, veterinario_id_veterinario)
    VALUES (v_id, p_data, p_anotacoes, p_valor, p_pet_id_pet, p_status_id_status, p_tipo_atend_id_tipo_atend, p_veterinario_id_veterinario);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_atendimento', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_atendimento', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_atendimento', USER, SQLCODE, SQLERRM);
END prc_insere_atendimento;
/

-- Procedure: inserir relacionamento usuario_pet
CREATE OR REPLACE PROCEDURE prc_insere_usuario_pet(
    p_usuario_id_usuario IN NUMBER,
    p_pet_id_pet IN NUMBER,
    p_respon_princ IN CHAR
) AS
BEGIN
    INSERT INTO usuario_pet (usuario_id_usuario, pet_id_pet, respon_princ)
    VALUES (p_usuario_id_usuario, p_pet_id_pet, p_respon_princ);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_usuario_pet', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_usuario_pet', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_usuario_pet', USER, SQLCODE, SQLERRM);
END prc_insere_usuario_pet;
/

-- Procedure: inserir relacionamento usuario_endereco
CREATE OR REPLACE PROCEDURE prc_insere_usuario_endereco(
    p_usuario_id_usuario IN NUMBER,
    p_endereco_id_endereco IN NUMBER
) AS
BEGIN
    INSERT INTO usuario_endereco (usuario_id_usuario, endereco_id_endereco)
    VALUES (p_usuario_id_usuario, p_endereco_id_endereco);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('prc_insere_usuario_endereco', USER, SQLCODE, 'Registro duplicado: ' || SQLERRM);
    WHEN VALUE_ERROR THEN
        prc_grava_log('prc_insere_usuario_endereco', USER, SQLCODE, 'Erro de valor: ' || SQLERRM);
    WHEN OTHERS THEN
        prc_grava_log('prc_insere_usuario_endereco', USER, SQLCODE, SQLERRM);
END prc_insere_usuario_endereco;
/

-- Fim das procedures de carga


-- =========================================================================
-- FIM DO ARQUIVO: 03_procedures_carga.sql
-- =========================================================================


-- =========================================================================
-- INÍCIO DO ARQUIVO: 04_blocos_anonimos_insercao.sql
-- =========================================================================

-- 04_blocos_anonimos_insercao.sql
-- Blocos anônimos que utilizam as procedures de carga criadas em 03_procedures_carga.sql
-- Cada bloco apresenta tratamento de exceção (WHEN OTHERS + 2 tratamentos extra)

-- 1) Inserção de dados de referência (raca, status, tipo_atend)
BEGIN
    prc_insere_raca(NULL, 'Vira-Lata');
    prc_insere_raca(NULL, 'Labrador');
    prc_insere_raca(NULL, 'Siamês');
    prc_insere_raca(NULL, 'Poodle');
    prc_insere_raca(NULL, 'Persa');
    
    prc_insere_status(NULL, 'PENDENTE');
    prc_insere_status(NULL, 'CONCLUIDO');
    prc_insere_status(NULL, 'EXPIRADO');
    
    prc_insere_tipo_atend(NULL, 'CONSULTA');
    prc_insere_tipo_atend(NULL, 'VACINACAO');
    prc_insere_tipo_atend(NULL, 'EXAME');
    prc_insere_tipo_atend(NULL, 'CIRURGIA');
    prc_insere_tipo_atend(NULL, 'CASTRACAO');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('bloco_ref_01', USER, SQLCODE, 'Registro duplicado em bloco de referencia: ' || SQLERRM);
        ROLLBACK;
        RAISE;

    WHEN VALUE_ERROR THEN
        prc_grava_log('bloco_ref_01', USER, SQLCODE, 'Erro de valor em bloco de referencia: ' || SQLERRM);
        ROLLBACK;
        RAISE;

    WHEN OTHERS THEN
        prc_grava_log('bloco_ref_01', USER, SQLCODE, SQLERRM);
        ROLLBACK;
        RAISE;
END;
/

-- 2) Inserção de telefones, endereco, bairro, cidade, estado, clinica
BEGIN
    prc_insere_telefone(NULL, '11', '999988877'); -- Tel Clinica / Vet / Maria (id 1)
    prc_insere_telefone(NULL, '21', '988776655'); -- Tel Joao (id 2)
    prc_insere_telefone(NULL, '11', '977776666'); -- Tel Pedro (id 3)
    prc_insere_telefone(NULL, '11', '966665555'); -- Tel Ana (id 4)
    prc_insere_telefone(NULL, '11', '955554444'); -- Tel Lucas (id 5)
    prc_insere_telefone(NULL, '11', '944443333'); -- Tel Dr. Carlos (id 6)
    prc_insere_telefone(NULL, '11', '933332222'); -- Tel Dra. Juliana (id 7)
    prc_insere_telefone(NULL, '11', '922221111'); -- Tel Dr. Marcos (id 8)
    
    prc_insere_estado(NULL, 'SP'); -- ID 1
    prc_insere_estado(NULL, 'RJ'); -- ID 2
    
    prc_insere_cidade(NULL, 'Sao Paulo', 1); -- ID 1 (SP)
    prc_insere_cidade(NULL, 'Rio de Janeiro', 2); -- ID 2 (RJ)
    
    prc_insere_bairro(NULL, 'Pinheiros', 1); -- ID 1 (SP)
    prc_insere_bairro(NULL, 'Copacabana', 2); -- ID 2 (RJ)
    prc_insere_bairro(NULL, 'Bela Vista', 1); -- ID 3 (SP)
    
    prc_insere_endereco(NULL, '05400000', 'Rua Exemplo SP', '123', 1); -- ID 1
    prc_insere_endereco(NULL, '02000000', 'Avenida Copacabana', '456', 2); -- ID 2
    prc_insere_endereco(NULL, '01311000', 'Avenida Paulista', '1000', 3); -- ID 3
    prc_insere_endereco(NULL, '05401000', 'Rua dos Pinheiros', '789', 1); -- ID 4
    
    prc_insere_clinica(NULL, 'Clinica Exemplo', 1, 1);

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('bloco_ref_02', USER, SQLCODE, 'Registro duplicado em bloco endereco/clinica: ' || SQLERRM);
        ROLLBACK;
        RAISE;

    WHEN VALUE_ERROR THEN
        prc_grava_log('bloco_ref_02', USER, SQLCODE, 'Erro de valor em bloco endereco/clinica: ' || SQLERRM);
        ROLLBACK;
        RAISE;

    WHEN OTHERS THEN
        prc_grava_log('bloco_ref_02', USER, SQLCODE, SQLERRM);
        ROLLBACK;
        RAISE;
END;
/

-- 3) Inserção de usuários, veterinarios e pets através das procedures
BEGIN
    -- Usuarios
    prc_insere_usuario(NULL, 'Joao Silva', 'joao@example.com', '123mudar', 2);
    prc_insere_usuario(NULL, 'Maria Souza', 'maria@example.com', '123mudar', 1);
    prc_insere_usuario(NULL, 'Pedro Santos', 'pedro@example.com', '123mudar', 3);
    prc_insere_usuario(NULL, 'Ana Oliveira', 'ana@example.com', '123mudar', 4);
    prc_insere_usuario(NULL, 'Lucas Lima', 'lucas@example.com', '123mudar', 5);
    
    -- Veterinarios (Carlos e Marcos com clinica, Juliana sem clinica [NULL])
    prc_insere_veterinario(NULL, 'Dr. Carlos', 'carlos@vet.com', '123mudar', 6, 1);
    prc_insere_veterinario(NULL, 'Dr. Marcos', 'marcos@vet.com', '123mudar', 8, 1);
    prc_insere_veterinario(NULL, 'Dra. Juliana', 'juliana@vet.com', '123mudar', 7, NULL);
    
    -- Pets (pelo menos 5 para o relatorio LAG/LEAD)
    prc_insere_pet(NULL, 'Rex', 5, 'M', 'GRANDE', 'S', 1);
    prc_insere_pet(NULL, 'Mimi', 3, 'F', 'PEQUENO', 'N', 3);
    prc_insere_pet(NULL, 'Thor', 2, 'M', 'MEDIO', 'S', 2);
    prc_insere_pet(NULL, 'Luna', 1, 'F', 'PEQUENO', 'N', 4);
    prc_insere_pet(NULL, 'Mel', 4, 'F', 'PEQUENO', 'S', 5);
    
    -- Relacionamentos usuario_pet (responsabilidade)
    -- Caso 1: 2 usuários cuidam de 1 pet (Rex - ID 1)
    prc_insere_usuario_pet(1, 1, 'S'); -- João responsável principal por Rex
    prc_insere_usuario_pet(2, 1, 'N'); -- Maria responsável secundária por Rex

    -- Caso 2: 2 usuários (Pedro e Ana) cuidam de 2 pets (Mimi [ID 2] e Thor [ID 3])
    prc_insere_usuario_pet(3, 2, 'S'); -- Pedro principal de Mimi
    prc_insere_usuario_pet(4, 2, 'N'); -- Ana secundária de Mimi
    prc_insere_usuario_pet(3, 3, 'N'); -- Pedro secundário de Thor
    prc_insere_usuario_pet(4, 3, 'S'); -- Ana principal de Thor

    -- Caso 3: 1 usuário cuida de 1 pet (Mel - ID 5)
    prc_insere_usuario_pet(5, 5, 'S'); -- Lucas principal de Mel

    -- Caso Extra: Luna (ID 4) cuidada por Maria
    prc_insere_usuario_pet(2, 4, 'S'); -- Maria principal de Luna
    
    -- Relacionamentos usuario_endereco (distribuindo os 5 endereços únicos)
    prc_insere_usuario_endereco(1, 1); -- João no Endereço 1
    prc_insere_usuario_endereco(2, 1); -- Maria no Endereço 1
    prc_insere_usuario_endereco(3, 2); -- Pedro no Endereço 2
    prc_insere_usuario_endereco(4, 3); -- Ana no Endereço 3
    prc_insere_usuario_endereco(5, 4); -- Lucas no Endereço 4

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        prc_grava_log('bloco_ref_03', USER, SQLCODE, 'Registro duplicado em bloco usuarios/veterinarios/pets: ' || SQLERRM);
        ROLLBACK;
        RAISE;

    WHEN VALUE_ERROR THEN
        prc_grava_log('bloco_ref_03', USER, SQLCODE, 'Erro de valor em bloco usuarios/veterinarios/pets: ' || SQLERRM);
        ROLLBACK;
        RAISE;

    WHEN OTHERS THEN
        prc_grava_log('bloco_ref_03', USER, SQLCODE, SQLERRM);
        ROLLBACK;
        RAISE;
END;
/

-- 4) Inserção de tarefas e atendimentos de exemplo
BEGIN
    DECLARE
        v_status_pendente NUMBER;
        v_status_concluido NUMBER;
        v_status_expirado NUMBER;
        v_tipo_consulta NUMBER;
        v_tipo_vacina NUMBER;
    BEGIN
        SELECT id_status INTO v_status_pendente FROM status WHERE nome_status = 'PENDENTE' AND ROWNUM = 1;
        SELECT id_status INTO v_status_concluido FROM status WHERE nome_status = 'CONCLUIDO' AND ROWNUM = 1;
        SELECT id_status INTO v_status_expirado FROM status WHERE nome_status = 'EXPIRADO' AND ROWNUM = 1;
        SELECT id_tipo_atend INTO v_tipo_consulta FROM tipo_atend WHERE tipo = 'CONSULTA' AND ROWNUM = 1;
        SELECT id_tipo_atend INTO v_tipo_vacina FROM tipo_atend WHERE tipo = 'VACINACAO' AND ROWNUM = 1;

        -- Inserção de Tarefas (Home-Care a serem realizadas pelos cuidadores)
        -- a) Tarefas que permanecem PENDENTES
        prc_insere_tarefa(1, 'Dar Remedio do Coracao', 15, 'Dar 1 comprimido de Benazepril pela manha antes do alimento', SYSTIMESTAMP, SYSTIMESTAMP + 1, NULL, 1, v_status_pendente, 1); -- Criado por Dr. Carlos (ID 1)
        prc_insere_tarefa(2, 'Restringir Exercicios', 20, 'Manter o pet em ambiente sem degraus e evitar pulos do sofa', SYSTIMESTAMP, SYSTIMESTAMP + 2, NULL, 1, v_status_pendente, 2);  -- Criado por Dra. Juliana (ID 2)
        prc_insere_tarefa(3, 'Limpar Cicatriz do Pet', 10, 'Higienizar a regiao dos pontos cirurgicos com soro fisiologico', SYSTIMESTAMP, SYSTIMESTAMP + 3, NULL, 3, v_status_pendente, 3); -- Criado por Dr. Marcos (ID 3)

        -- b) Tarefas que iniciam pendentes e serão concluídas pelos usuários (histórico de cuidados realizados)
        prc_insere_tarefa(4, 'Caminhada Fisioterapia', 25, 'Realizar passeio leve de no maximo 10 minutos na grama plana', SYSTIMESTAMP - 5, SYSTIMESTAMP - 4, NULL, 4, v_status_pendente, 1); -- Criado por Dr. Carlos (ID 1)
        prc_insere_tarefa(5, 'Oferecer Racao Renal', 8, 'Fornecer 80g de racao renal umida no pote higienizado', SYSTIMESTAMP - 2, SYSTIMESTAMP - 1, NULL, 5, v_status_pendente, 2);      -- Criado por Dra. Juliana (ID 2)
        prc_insere_tarefa(6, 'Aplicar Pomada Otologica', 12, 'Passar 3 gotas de pomada no ouvido esquerdo apos limpeza', SYSTIMESTAMP - 3, SYSTIMESTAMP - 2, NULL, 1, v_status_pendente, 1);  -- Criado por Dr. Carlos (ID 1)

        -- Execução da conclusão das tarefas (simula a interação dos usuários)
        prc_concluir_tarefa(4, 2, SYSTIMESTAMP - 4.5); -- Maria Souza (ID 2) conclui a tarefa 4
        prc_concluir_tarefa(5, 5, SYSTIMESTAMP - 1.5); -- Lucas Lima (ID 5) conclui a tarefa 5
        prc_concluir_tarefa(6, 1, SYSTIMESTAMP - 2.5); -- Joao Silva (ID 1) conclui a tarefa 6

        -- c) Tarefas que já nascem EXPIRADAS (não foram feitas a tempo)
        prc_insere_tarefa(7, 'Trocar Agua da Fonte', 15, 'Limpar a fonte de agua e abastecer com agua fresca e gelada', SYSTIMESTAMP - 10, SYSTIMESTAMP - 9, NULL, 3, v_status_expirado, 3); -- Criado por Dr. Marcos (ID 3)
        prc_insere_tarefa(8, 'Escovar Pelo Diariamente', 5, 'Escovacao suave para remover pelos mortos e ajudar na dermatite', SYSTIMESTAMP - 8, SYSTIMESTAMP - 7, NULL, 1, v_status_expirado, 2); -- Criado por Dra. Juliana (ID 2)

        -- Inserção de Atendimentos (Simulação de atendimentos em andamento, concluídos e cancelados/expirados)
        prc_insere_atendimento(NULL, SYSTIMESTAMP - 3, 'Consulta geral de rotina', 120.00, 1, v_status_concluido, v_tipo_consulta, 1); -- Concluído (Dr. Carlos)
        prc_insere_atendimento(NULL, SYSTIMESTAMP - 2, 'Aplicacao de vacina V10', 85.00, 2, v_status_concluido, v_tipo_vacina, 2);     -- Concluído (Dra. Juliana)
        prc_insere_atendimento(NULL, SYSTIMESTAMP - 1, 'Consulta dermatologica especial', 180.00, 3, v_status_concluido, v_tipo_consulta, 3); -- Concluído (Dr. Marcos)
        prc_insere_atendimento(NULL, SYSTIMESTAMP, 'Exame clinico e check-up', 95.00, 4, v_status_pendente, v_tipo_consulta, 1);         -- Pendente (Dr. Carlos)
        prc_insere_atendimento(NULL, SYSTIMESTAMP, 'Consulta de urgência febre', 210.00, 5, v_status_expirado, v_tipo_consulta, 2);       -- Expirado (Dra. Juliana)

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            prc_grava_log('bloco_ref_04', USER, SQLCODE, 'Status ou tipo de atendimento nao encontrado para insercao de tarefas/atendimentos');
            ROLLBACK;
            RAISE;

        WHEN VALUE_ERROR THEN
            prc_grava_log('bloco_ref_04', USER, SQLCODE, 'Erro de valor ao inserir tarefas/atendimentos: ' || SQLERRM);
            ROLLBACK;
            RAISE;

        WHEN OTHERS THEN
            prc_grava_log('bloco_ref_04', USER, SQLCODE, SQLERRM);
            ROLLBACK;
            RAISE;
    END;
END;
/

-- =========================================================================
-- FIM DO ARQUIVO: 04_blocos_anonimos_insercao.sql
-- =========================================================================


-- =========================================================================
-- INÍCIO DO ARQUIVO: 05_consultas_joins.sql
-- =========================================================================

-- 05_consultas_joins.sql
-- Blocos anônimos com consultas de join, group by e order by
-- Ambos os blocos utilizam pelo menos 3 consultas com JOIN, GROUP BY e ORDER BY no total.

SET SERVEROUTPUT ON;

-- Bloco 1: Consultas de agrupamento de tarefas por pet e por veterinário
BEGIN
	DBMS_OUTPUT.PUT_LINE('=== BLOCO 1: AGRUPAMENTOS DE TAREFAS ===');
	
	DBMS_OUTPUT.PUT_LINE('--- 1) Quantidade de Tarefas por Pet ---');
	FOR r1 IN (
		SELECT p.nome AS nome_pet, COUNT(t.id_tarefa) AS qtd_tarefas
		FROM tarefa t
		JOIN pet p ON t.pet_id_pet = p.id_pet
		GROUP BY p.nome
		ORDER BY qtd_tarefas DESC, p.nome ASC
	) LOOP
		DBMS_OUTPUT.PUT_LINE('Pet: ' || r1.nome_pet || ' | Qtd Tarefas: ' || r1.qtd_tarefas);
	END LOOP;

	DBMS_OUTPUT.PUT_LINE('--- 2) Quantidade de Tarefas Criadas por Veterinario ---');
	FOR r2 IN (
		SELECT v.nome AS nome_veterinario, COUNT(t.id_tarefa) AS qtd_tarefas
		FROM tarefa t
		JOIN veterinario v ON t.veterinario_id_veterinario = v.id_veterinario
		GROUP BY v.nome
		ORDER BY qtd_tarefas DESC, v.nome ASC
	) LOOP
		DBMS_OUTPUT.PUT_LINE('Vet Criador: ' || r2.nome_veterinario || ' | Qtd Tarefas Criadas: ' || r2.qtd_tarefas);
	END LOOP;

EXCEPTION
	WHEN NO_DATA_FOUND THEN
		prc_grava_log('bloco_consulta_01', USER, SQLCODE, 'Nenhum dado encontrado: ' || SQLERRM);
		ROLLBACK;
		RAISE;
	WHEN VALUE_ERROR THEN
		prc_grava_log('bloco_consulta_01', USER, SQLCODE, 'Erro de valor na consulta: ' || SQLERRM);
		ROLLBACK;
		RAISE;
	WHEN OTHERS THEN
		prc_grava_log('bloco_consulta_01', USER, SQLCODE, SQLERRM);
		ROLLBACK;
		RAISE;
END;
/

-- Bloco 2: Sumarizações de status, faturamento de consultas e posse de pets
BEGIN
	DBMS_OUTPUT.PUT_LINE('=== BLOCO 2: SUMARIZACOES E METRICAS ===');

	DBMS_OUTPUT.PUT_LINE('--- 3) Quantidade de tarefas por status ---');
	FOR r1 IN (
		SELECT s.nome_status, COUNT(*) AS qtd_tarefas
		FROM tarefa t
		JOIN status s ON t.status_id_status = s.id_status
		GROUP BY s.nome_status
		ORDER BY qtd_tarefas DESC
	) LOOP
		DBMS_OUTPUT.PUT_LINE(r1.nome_status || ': ' || r1.qtd_tarefas);
	END LOOP;

	DBMS_OUTPUT.PUT_LINE('--- 4) Valor total de atendimentos por veterinario ---');
	FOR r2 IN (
		SELECT v.nome AS veterinario, NVL(SUM(a.valor),0) AS total_atendimentos
		FROM atendimento a
		JOIN veterinario v ON a.veterinario_id_veterinario = v.id_veterinario
		GROUP BY v.nome
		ORDER BY total_atendimentos DESC
	) LOOP
		DBMS_OUTPUT.PUT_LINE(r2.veterinario || ': R$ ' || TO_CHAR(r2.total_atendimentos,'99999990.00'));
	END LOOP;

	DBMS_OUTPUT.PUT_LINE('--- 5) Quantidade de pets por usuario (responsaveis) ---');
	FOR r3 IN (
		SELECT u.nome AS usuario, COUNT(up.pet_id_pet) AS qtd_pets
		FROM usuario u
		JOIN usuario_pet up ON u.id_usuario = up.usuario_id_usuario
		GROUP BY u.nome
		ORDER BY qtd_pets DESC
	) LOOP
		DBMS_OUTPUT.PUT_LINE(r3.usuario || ': ' || r3.qtd_pets);
	END LOOP;

EXCEPTION
	WHEN NO_DATA_FOUND THEN
		prc_grava_log('bloco_consulta_02', USER, SQLCODE, 'Nenhum dado encontrado nas sumarizacoes: ' || SQLERRM);
		ROLLBACK;
		RAISE;
	WHEN VALUE_ERROR THEN
		prc_grava_log('bloco_consulta_02', USER, SQLCODE, 'Erro de valor nas sumarizacoes: ' || SQLERRM);
		ROLLBACK;
		RAISE;
	WHEN OTHERS THEN
		prc_grava_log('bloco_consulta_02', USER, SQLCODE, SQLERRM);
		ROLLBACK;
		RAISE;
END;
/


-- =========================================================================
-- FIM DO ARQUIVO: 05_consultas_joins.sql
-- =========================================================================


-- =========================================================================
-- INÍCIO DO ARQUIVO: 06_consulta_valor_anterior_proximo.sql
-- =========================================================================

SET SERVEROUTPUT ON;

-- Bloco anônimo: para cada pet mostrar nome atual, nome anterior e nome próximo
BEGIN
    DECLARE
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_cnt FROM pet;
        IF v_cnt < 5 THEN
            RAISE NO_DATA_FOUND;
        END IF;
        DBMS_OUTPUT.PUT_LINE('id_pet | nome_atual | nome_anterior | nome_proximo');
        FOR r IN (
            SELECT id_pet,
                   nome AS nome_atual,
                   NVL(LAG(nome) OVER (ORDER BY id_pet), 'Vazio') AS nome_anterior,
                   NVL(LEAD(nome) OVER (ORDER BY id_pet), 'Vazio') AS nome_proximo
            FROM pet
            ORDER BY id_pet
        ) LOOP
            DBMS_OUTPUT.PUT_LINE(r.id_pet || ' | ' || r.nome_atual || ' | ' || r.nome_anterior || ' | ' || r.nome_proximo);
        END LOOP;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            prc_grava_log('bloco_valor_anterior_proximo', USER, SQLCODE, 'Relatório requer ao menos 5 pets cadastrados');

        WHEN VALUE_ERROR THEN
            prc_grava_log('bloco_valor_anterior_proximo', USER, SQLCODE, 'Erro de valor no relatório: ' || SQLERRM);

        WHEN OTHERS THEN
            prc_grava_log('bloco_valor_anterior_proximo', USER, SQLCODE, SQLERRM);
    END;
END;
/

-- Nota: assegure que a tabela PET possua ao menos 5 linhas para relatório com cinco entradas.

-- =========================================================================
-- FIM DO ARQUIVO: 06_consulta_valor_anterior_proximo.sql
-- =========================================================================


-- =========================================================================
-- INÍCIO DO ARQUIVO: 07_relatorios_cursors.sql
-- =========================================================================

SET SERVEROUTPUT ON;

-- 1) Listar todas as tarefas, sumarizar pontos totais e por status
BEGIN
    DECLARE
        CURSOR c_tarefas IS
            SELECT id_tarefa, titulo, pontos_tarefa, status_id_status FROM tarefa;

        v_total_pontos NUMBER := 0;
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM tarefa;

        IF v_count = 0 THEN
            RAISE NO_DATA_FOUND;
        END IF;

        DBMS_OUTPUT.PUT_LINE('=== RELATORIO 1: DETALHAMENTO DE TAREFAS E PONTOS ===');
        FOR r IN c_tarefas LOOP
            DBMS_OUTPUT.PUT_LINE('Tarefa: ' || r.titulo || ' | Pontos: ' || r.pontos_tarefa || ' | Status: ' || r.status_id_status);
            v_total_pontos := v_total_pontos + NVL(r.pontos_tarefa,0);
            
            -- Tomada de decisão baseada nos pontos da tarefa
            IF r.pontos_tarefa >= 20 THEN
                DBMS_OUTPUT.PUT_LINE('   -> Prioridade: ALTA (Impacto relevante no cuidado)');
            ELSIF r.pontos_tarefa >= 10 THEN
                DBMS_OUTPUT.PUT_LINE('   -> Prioridade: MEDIA');
            ELSE
                DBMS_OUTPUT.PUT_LINE('   -> Prioridade: BAIXA');
            END IF;
            DBMS_OUTPUT.PUT_LINE(' '); -- Espaço entre as tarefas
        END LOOP;

        DBMS_OUTPUT.PUT_LINE('---------------------------------------------------');
        DBMS_OUTPUT.PUT_LINE('Valor Numérico Sumarizado (Total de Pontos): ' || v_total_pontos);
        DBMS_OUTPUT.PUT_LINE('---------------------------------------------------');
        DBMS_OUTPUT.PUT_LINE('Sumarização de Pontos por Status do Agrupamento:');

        FOR r2 IN (
            SELECT s.nome_status, SUM(t.pontos_tarefa) AS soma
            FROM tarefa t
            JOIN status s ON t.status_id_status = s.id_status
            GROUP BY s.nome_status
        ) LOOP
            DBMS_OUTPUT.PUT_LINE('Status: ' || r2.nome_status || ' | Pontos acumulados: ' || r2.soma);
        END LOOP;
        
        DBMS_OUTPUT.PUT_LINE('---------------------------------------------------');
        DBMS_OUTPUT.PUT_LINE('Carga Total de Pontos em Tarefas dos Pets de cada Responsável:');
        FOR r3 IN (
            SELECT u.nome, SUM(t.pontos_tarefa) AS soma_cuidador
            FROM usuario u
            JOIN usuario_pet up ON u.id_usuario = up.usuario_id_usuario
            JOIN tarefa t ON up.pet_id_pet = t.pet_id_pet
            GROUP BY u.nome
            ORDER BY soma_cuidador DESC
        ) LOOP
            DBMS_OUTPUT.PUT_LINE('Responsável: ' || r3.nome || ' | Pontos sob cuidados: ' || r3.soma_cuidador);
        END LOOP;
        
        DBMS_OUTPUT.PUT_LINE('---------------------------------------------------');
        DBMS_OUTPUT.PUT_LINE('Pontos Efetivamente Ganhos por Conclusao de Tarefa (Realizadas):');
        FOR r4 IN (
            SELECT u.nome, SUM(t.pontos_tarefa) AS soma_ganhos
            FROM usuario u
            JOIN tarefa t ON u.id_usuario = t.usuario_id_usuario
            GROUP BY u.nome
            ORDER BY soma_ganhos DESC
        ) LOOP
            DBMS_OUTPUT.PUT_LINE('Responsável Executor: ' || r4.nome || ' | Pontos Ganhos: ' || r4.soma_ganhos);
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('===================================================');

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            prc_grava_log('relatorio_tarefas', USER, SQLCODE, 'Nenhuma tarefa encontrada: ' || SQLERRM);

        WHEN VALUE_ERROR THEN
            prc_grava_log('relatorio_tarefas', USER, SQLCODE, 'Erro de valor no relatório de tarefas: ' || SQLERRM);

        WHEN OTHERS THEN
            prc_grava_log('relatorio_tarefas', USER, SQLCODE, SQLERRM);
    END;
END;
/

-- 2) Listar pets castrados e não castrados usando cursor e decisão
BEGIN
    DECLARE
        CURSOR c_pets IS
            SELECT id_pet, nome, castrado FROM pet ORDER BY id_pet;

        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM pet;

        IF v_count = 0 THEN
            RAISE NO_DATA_FOUND;
        END IF;

        FOR r IN c_pets LOOP
            IF r.castrado = 'S' THEN
                DBMS_OUTPUT.PUT_LINE(r.id_pet || ' - ' || r.nome || ': castrado');

            ELSIF r.castrado = 'N' THEN
                DBMS_OUTPUT.PUT_LINE(r.id_pet || ' - ' || r.nome || ': não castrado');

            ELSE
                DBMS_OUTPUT.PUT_LINE(r.id_pet || ' - ' || r.nome || ': castrado desconhecido');
            END IF;
        END LOOP;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            prc_grava_log('relatorio_pets_castracao', USER, SQLCODE, 'Nenhum pet encontrado: ' || SQLERRM);

        WHEN VALUE_ERROR THEN
            prc_grava_log('relatorio_pets_castracao', USER, SQLCODE, 'Erro de valor no relatório de castração: ' || SQLERRM);

        WHEN OTHERS THEN
            prc_grava_log('relatorio_pets_castracao', USER, SQLCODE, SQLERRM);
    END;
END;
/

-- 3) Listar atendimentos e indicar se valor é alto (>100)
BEGIN
    DECLARE
        CURSOR c_atend IS
            SELECT id_atendimento, valor FROM atendimento ORDER BY id_atendimento;

        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM atendimento;

        IF v_count = 0 THEN
            RAISE NO_DATA_FOUND;
        END IF;

        FOR r IN c_atend LOOP
            IF r.valor > 100 THEN
                DBMS_OUTPUT.PUT_LINE('Atendimento ' || r.id_atendimento || ': valor ALTO (' || TO_CHAR(r.valor,'99999990.00') || ')');

            ELSE
                DBMS_OUTPUT.PUT_LINE('Atendimento ' || r.id_atendimento || ': valor normal (' || TO_CHAR(r.valor,'99999990.00') || ')');
            END IF;
        END LOOP;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            prc_grava_log('relatorio_atendimentos', USER, SQLCODE, 'Nenhum atendimento encontrado: ' || SQLERRM);

        WHEN VALUE_ERROR THEN
            prc_grava_log('relatorio_atendimentos', USER, SQLCODE, 'Erro de valor no relatório de atendimentos: ' || SQLERRM);

        WHEN OTHERS THEN
            prc_grava_log('relatorio_atendimentos', USER, SQLCODE, SQLERRM);
    END;
END;
/

-- 4) Listar usuários e informar se possuem telefone cadastrado
BEGIN
    DECLARE
        CURSOR c_usuarios IS
            SELECT id_usuario, nome, telefone_id_telefone FROM usuario ORDER BY nome;

        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM usuario;

        IF v_count = 0 THEN
            RAISE NO_DATA_FOUND;
        END IF;

        FOR r IN c_usuarios LOOP
            IF r.telefone_id_telefone IS NOT NULL THEN
                DBMS_OUTPUT.PUT_LINE(r.id_usuario || ' - ' || r.nome || ': possui telefone');

            ELSE
                DBMS_OUTPUT.PUT_LINE(r.id_usuario || ' - ' || r.nome || ': sem telefone');
            END IF;
        END LOOP;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            prc_grava_log('relatorio_usuarios_telefone', USER, SQLCODE, 'Nenhum usuário encontrado: ' || SQLERRM);

        WHEN VALUE_ERROR THEN
            prc_grava_log('relatorio_usuarios_telefone', USER, SQLCODE, 'Erro de valor no relatório de usuários: ' || SQLERRM);

        WHEN OTHERS THEN
            prc_grava_log('relatorio_usuarios_telefone', USER, SQLCODE, SQLERRM);
    END;
END;
/

-- =========================================================================
-- FIM DO ARQUIVO: 07_relatorios_cursors.sql
-- =========================================================================

