-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-09 16:10:49 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE atendimento 
    ( 
     id_atendimento             RAW (4)  NOT NULL , 
     data                       DATE  NOT NULL , 
     anotacoes                  VARCHAR2 (100) , 
     veterinaria_id_veterinaria RAW (5)  NOT NULL , 
     pet_id_pet                 RAW (5)  NOT NULL , 
     pet_id_familia             RAW (3)  NOT NULL 
    ) 
;

ALTER TABLE atendimento 
    ADD CONSTRAINT atendimento_PK PRIMARY KEY ( id_atendimento, veterinaria_id_veterinaria, pet_id_pet, pet_id_familia ) ;

CREATE TABLE endereco 
    ( 
     id_endereco RAW (4)  NOT NULL , 
     rua         VARCHAR2 (100)  NOT NULL , 
     bairro      VARCHAR2 (50)  NOT NULL , 
     cidade      VARCHAR2 (50)  NOT NULL , 
     estado      VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE endereco 
    ADD CONSTRAINT endereco_PK PRIMARY KEY ( id_endereco ) ;

CREATE TABLE familia 
    ( 
     id_familia RAW (3)  NOT NULL 
    ) 
;

ALTER TABLE familia 
    ADD CONSTRAINT familia_PK PRIMARY KEY ( id_familia ) ;

CREATE TABLE pet 
    ( 
     id_pet             RAW (5)  NOT NULL , 
     raca               VARCHAR2 (20)  NOT NULL , 
     porte              NUMBER (5,2)  NOT NULL , 
     sexo               CHAR (1)  NOT NULL , 
     nascimento         DATE  NOT NULL , 
     familia_id_familia RAW (3)  NOT NULL 
    ) 
;

ALTER TABLE pet 
    ADD CONSTRAINT pet_PK PRIMARY KEY ( id_pet, familia_id_familia ) ;

CREATE TABLE tarefa 
    ( 
     id_tarefa          RAW (5)  NOT NULL , 
     criacao            DATE  NOT NULL , 
     prazo              DATE  NOT NULL , 
     estado             CHAR (1)  NOT NULL , 
     usuario_id_usuario RAW (5)  NOT NULL , 
     usuario_id_familia RAW (3)  NOT NULL , 
     pet_id_pet         RAW (5)  NOT NULL , 
     pet_id_familia     RAW (3)  NOT NULL 
    ) 
;

ALTER TABLE tarefa 
    ADD CONSTRAINT tarefa_PK PRIMARY KEY ( id_tarefa, usuario_id_usuario, usuario_id_familia, pet_id_pet, pet_id_familia ) ;

CREATE TABLE usuario 
    ( 
     id_usuario           RAW (5)  NOT NULL , 
     nome                 VARCHAR2 (100)  NOT NULL , 
     senha                VARCHAR2 (20)  NOT NULL , 
     telefone             VARCHAR2 (11)  NOT NULL , 
     familia_id_familia   RAW (3)  NOT NULL , 
     endereco_id_endereco RAW (4)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX usuario__IDX ON usuario 
    ( 
     endereco_id_endereco ASC 
    ) 
;

ALTER TABLE usuario 
    ADD CONSTRAINT usuario_PK PRIMARY KEY ( id_usuario, familia_id_familia ) ;

CREATE TABLE veterinaria 
    ( 
     id_veterinaria       RAW (5)  NOT NULL , 
     endereco_id_endereco RAW (4)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX veterinaria__IDX ON veterinaria 
    ( 
     endereco_id_endereco ASC 
    ) 
;

ALTER TABLE veterinaria 
    ADD CONSTRAINT veterinaria_PK PRIMARY KEY ( id_veterinaria ) ;

ALTER TABLE atendimento 
    ADD CONSTRAINT atendimento_pet_FK FOREIGN KEY 
    ( 
     pet_id_pet,
     pet_id_familia
    ) 
    REFERENCES pet 
    ( 
     id_pet,
     familia_id_familia
    ) 
;

ALTER TABLE atendimento 
    ADD CONSTRAINT atendimento_veterinaria_FK FOREIGN KEY 
    ( 
     veterinaria_id_veterinaria
    ) 
    REFERENCES veterinaria 
    ( 
     id_veterinaria
    ) 
;

ALTER TABLE pet 
    ADD CONSTRAINT pet_familia_FK FOREIGN KEY 
    ( 
     familia_id_familia
    ) 
    REFERENCES familia 
    ( 
     id_familia
    ) 
;

ALTER TABLE tarefa 
    ADD CONSTRAINT tarefa_pet_FK FOREIGN KEY 
    ( 
     pet_id_pet,
     pet_id_familia
    ) 
    REFERENCES pet 
    ( 
     id_pet,
     familia_id_familia
    ) 
;

ALTER TABLE tarefa 
    ADD CONSTRAINT tarefa_usuario_FK FOREIGN KEY 
    ( 
     usuario_id_usuario,
     usuario_id_familia
    ) 
    REFERENCES usuario 
    ( 
     id_usuario,
     familia_id_familia
    ) 
;

ALTER TABLE usuario 
    ADD CONSTRAINT usuario_endereco_FK FOREIGN KEY 
    ( 
     endereco_id_endereco
    ) 
    REFERENCES endereco 
    ( 
     id_endereco
    ) 
;

ALTER TABLE usuario 
    ADD CONSTRAINT usuario_familia_FK FOREIGN KEY 
    ( 
     familia_id_familia
    ) 
    REFERENCES familia 
    ( 
     id_familia
    ) 
;

ALTER TABLE veterinaria 
    ADD CONSTRAINT veterinaria_endereco_FK FOREIGN KEY 
    ( 
     endereco_id_endereco
    ) 
    REFERENCES endereco 
    ( 
     id_endereco
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             2
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
